# --------------------
# Resonance Type - List of valid resonance particle (w. different decay topology)
# --------------------
HadronicTop:
  th/bqq:
    Mass: 172.76
    Spin: 0.5
    nProduct_BJet: 1
    nProduct_Jet: 3
    nProduct_Lepton: 0
    Product_LeptonCharge: 0
    # this is for segmentation head, starting from 1 (0 is reserved for no decay)
    segment_tag: 1

LeptonicTop:
  tl/bl:
    Mass: 172.76
    Spin: 0.5
    nProduct_BJet: 1
    nProduct_Jet: 1
    nProduct_Lepton: 1
    # this is for segmentation head, starting from 1 (0 is reserved for no decay)
    segment_tag: 2

